version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: projectwithdocker_app 
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: projectwithdocker
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
